### ISSUE TITLE
Trailers not playing on personal media?

### ISSUE THREAD

**Issue by 4jy** [piplongrun/TrailerAddict.bundle#18]
I am trying to get trailers to play on my personal media under movies but no trailers play. I've selected TrailerAddict for "PlexMovie" and "The Movie Database"

**Comment by piplongrun** [comment]
Trailer Addict requires the PlexMovie or The Movie Database agent, as stated under [Requirements](https://github.com/piplongrun/TrailerAddict.bundle/blob/master/README.md#requirements) in the [README](https://github.com/piplongrun/TrailerAddict.bundle/blob/master/README.md).

Trailer Addict is not written for personal media, because it can only work when a valid IMDB id is provided by one of the beforementioned primary agents.
