### ISSUE TITLE
Not downloading trailers

### ISSUE THREAD

**Issue by weasilva** [piplongrun/TrailerAddict.bundle#27]
Hi. I used this plugin for the first time last year and that’s awesome! But lately I am no longer able to download. I checked the log and get the following error:
```
  File "C:\Users\wesll\AppData\Local\Plex Media Server\Plug-ins\TrailerAddict.bundle\Contents\Libraries\Shared\requests\adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='api.tadata.me', port=443): Max retries exceeded with url: /imdb2ta/v2/?imdb_id=tt5095030 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0380F950>: Failed to establish a new connection: [Errno 10060] Uma tentativa de conex\xe3o falhou porque o componente conectado n\xe3o respondeu\r\ncorretamente ap\xf3s um per\xedodo de tempo ou a conex\xe3o estabelecida falhou\r\nporque o host conectado n\xe3o respondeu',))
```

**Comment by piplongrun** [comment]
The only thing I can think of is that somehow the firewall got triggered by a certain request and you are now blocked from the server, my server in this case (sorry about that in advance :-o). Can you send me [your ip address](http://www.whatsmyip.org/) so I can check if this is the case? You can email me at pip.longrun@protonmail.com if you don't like sharing your ip address in here.

**Comment by weasilva** [comment]
Thanks. I sent you my IP address by email.

**Comment by piplongrun** [comment]
Hi and thank you!

I haven't been able to find out why exactly yet, but somehow a number of ip addresses in the block yours is also from got blocked (probably due to spam or brute force attacks). If all went well you are now able to use the agent again. Please let me know if it still doesn't work for you.

Thanks!
-Pip



‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by piplongrun** [comment]
Oops, I forgot to reload the new firewall rules after making changes, sorry! It should work now :)



‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by weasilva** [comment]
It's working now. 👍  Thank you so much! U're the Best!

**Comment by piplongrun** [comment]
> It's working now. 👍  Thank you so much! U're the Best!

Thanks! Glad to hear it is all working again! I learn a lot from all those moments when things break or go wrong ;-)

**Comment by abielrodriguez** [comment]
Hello I'm having a similar issue, I'm wondering if I might be being blocked by the Firewall as well:


#588 | raise ConnectionError(e, request=request)
-- | --
#589 | ConnectionError: HTTPSConnectionPool(host='api.tadata.me', port=443): Max retries exceeded with url: /imdb2ta/v2/?imdb_id=tt0055254 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa3ac622890>: Failed to establish a new connection: [Errno 110] Connection timed out',))

**Comment by piplongrun** [comment]
@abielrodriguez That looks very similar, can you please [email me](mailto:pip.longrun@protonmail.com) [your ip address](http://www.whatsmyip.org/) so I can check if this is indeed a firewall issue.

**Comment by abielrodriguez** [comment]
Done!

**Comment by piplongrun** [comment]
@abielrodriguez Can you try again? I think it is fixed now.

**Comment by abielrodriguez** [comment]
Will do!

**Comment by abielrodriguez** [comment]
It’s working now! Thanks for the help :)
